Hotel_test1/Models/BOOKING.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_test1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class BOOKING
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOOKING()
        {
            this.BILLs = new HashSet<BILL>();
        }
        public string Booking_id { get; set; }

        [DisplayName("Ngày nhận phòng")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime Check_in_date { get; set; }

        [DisplayName("Ngày trả phòng")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime Check_out_date { get; set; }

        [DisplayName("Mã khách hàng")]
        public string Customer_id { get; set; }
        [DisplayName("Mã phòng")]
        public string Room_id { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILL> BILLs { get; set; }
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual ROOM ROOM { get; set; }
    }
}

Hotel_test1/Controllers/BOOKINGsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Hotel_test1.Models;

namespace Hotel_test1.Controllers
{
    public class BOOKINGsController : Controller
    {
        private HOTEL3Entities db = new HOTEL3Entities();

        // GET: BOOKINGs
        public ActionResult Index(string searchString, string category)
        {
            if (Session["AdminId"] == null || Session["AdminId"].ToString() == "")
            {
                return RedirectToAction("Login", "Admin");
            }

            var bOOKINGs = db.BOOKINGs.Include(b => b.CUSTOMER).Include(b => b.ROOM);


            if (!String.IsNullOrEmpty(searchString))
            {
                if (!String.IsNullOrEmpty(category))
                {
                    ViewBag.category = category;

                    switch (category)
                    {
                        case "Booking_id":
                            bOOKINGs = bOOKINGs.Where(s => s.Booking_id.Contains(searchString));
                            break;
                        case "CustomerLastName":
                            bOOKINGs = bOOKINGs.Where(s => s.CUSTOMER.CustomerFirstName.Contains(searchString));
                            break;
                        case "CustomerFirstName":
                            bOOKINGs = bOOKINGs.Where(s => s.CUSTOMER.CustomerFirstName.Contains(searchString));
                            break;
                        case "RType":
                            bOOKINGs = bOOKINGs.Where(s => s.ROOM.ROOMTYPE.RType.Contains(searchString));
                            break;
                        case "Room_id":
                            bOOKINGs = bOOKINGs.Where(s => s.ROOM.Room_id.Contains(searchString));
                            break;
                    }
                }
            }




            return View(bOOKINGs.ToList());
        }

        // GET: BOOKINGs/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BOOKING bOOKING = db.BOOKINGs.Find(id);
            if (bOOKING == null)
            {
                return HttpNotFound();
            }
            return View(bOOKING);
        }

        // GET: BOOKINGs/Create
        public ActionResult Create()
        {
            ViewBag.Customer_id = new SelectList(db.CUSTOMERs, "Customer_id", "CustomerFirstName");
            ViewBag.Room_id = new SelectList(db.ROOMs, "Room_id", "RoomType_id");
            return View();
        }

        // POST: BOOKINGs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Booking_id,Check_in_date,Check_out_date,Customer_id,Room_id")] BOOKING bOOKING)
        {
            if (ModelState.IsValid)
            {
                db.BOOKINGs.Add(bOOKING);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Customer_id = new SelectList(db.CUSTOMERs, "Customer_id", "CustomerFirstName", bOOKING.Customer_id);
            ViewBag.Room_id = new SelectList(db.ROOMs, "Room_id", "RoomType_id", bOOKING.Room_id);
            return View(bOOKING);
        }

        // GET: BOOKINGs/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BOOKING bOOKING = db.BOOKINGs.Find(id);
            if (bOOKING == null)
            {
                return HttpNotFound();
            }
            ViewBag.Customer_id = new SelectList(db.CUSTOMERs, "Customer_id", "CustomerFirstName", bOOKING.Customer_id);
            ViewBag.Room_id = new SelectList(db.ROOMs, "Room_id", "RoomType_id", bOOKING.Room_id);
            return View(bOOKING);
        }

        // POST: BOOKINGs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Booking_id,Check_in_date,Check_out_date,Customer_id,Room_id")] BOOKING bOOKING)
        {
            if (ModelState.IsValid)
            {
                db.Entry(bOOKING).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Customer_id = new SelectList(db.CUSTOMERs, "Customer_id", "CustomerFirstName", bOOKING.Customer_id);
            ViewBag.Room_id = new SelectList(db.ROOMs, "Room_id", "RoomType_id", bOOKING.Room_id);
            return View(bOOKING);
        }

        // GET: BOOKINGs/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BOOKING bOOKING = db.BOOKINGs.Find(id);
            if (bOOKING == null)
            {
                return HttpNotFound();
            }
            return View(bOOKING);
        }

        // POST: BOOKINGs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            BOOKING bOOKING = db.BOOKINGs.Find(id);
            var s = db.BILLs.Where(u => u.Booking_id == bOOKING.Booking_id).ToList();

            if (s != null && s.Count > 0)
            {
                db.BILLs.Remove(s[0]);
            }

            db.BOOKINGs.Remove(bOOKING);

            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Hotel_test1/Views/BOOKINGs/Create.cshtml
@model Hotel_test1.Models.BOOKING

@{
    ViewBag.Title = "Thêm booking";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>BOOKING</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Booking_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Booking_id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Booking_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Check_in_date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Check_in_date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Check_in_date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Check_out_date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Check_out_date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Check_out_date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Customer_id, "Customer_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Customer_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Customer_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Room_id, "Room_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Room_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Room_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Hotel_test1/Views/BOOKINGs/Delete.cshtml
@model Hotel_test1.Models.BOOKING

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BOOKING</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Check_in_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Check_in_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Check_out_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Check_out_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CUSTOMER.CustomerFirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CUSTOMER.CustomerFirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ROOM.RoomType_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ROOM.RoomType_id)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Hotel_test1/Views/BOOKINGs/Details.cshtml
@model Hotel_test1.Models.BOOKING

@{
    ViewBag.Title = "Thông tin chi tiết";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>BOOKING</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Check_in_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Check_in_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Check_out_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Check_out_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CUSTOMER.CustomerFirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CUSTOMER.CustomerFirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ROOM.RoomType_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ROOM.RoomType_id)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Booking_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Hotel_test1/Views/BOOKINGs/Edit.cshtml
@model Hotel_test1.Models.BOOKING

@{
    ViewBag.Title = "Chỉnh sửa booking";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>BOOKING</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Booking_id)

        <div class="form-group">
            @Html.LabelFor(model => model.Check_in_date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Check_in_date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Check_in_date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Check_out_date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Check_out_date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Check_out_date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Customer_id, "Customer_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Customer_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Customer_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Room_id, "Room_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Room_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Room_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Hotel_test1/Views/BOOKINGs/Index.cshtml
@model IEnumerable<Hotel_test1.Models.BOOKING>

@{
    ViewBag.Title = "Danh sách booking";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    var grid = new WebGrid(Model, canPage: true, defaultSort: "Booking_id", rowsPerPage: 5);
}

    @using (Html.BeginForm("Index", "BOOKINGs", FormMethod.Get))
    {
    <p>
        

                @Html.TextBox("SearchString")
                <select name="category" id="category">
        
                    <option value="Booking_id" id="Booking_id">Mã Book</option>
        
                    <option value="CustomerLastName" id="CustomerLastName">Họ khách hàng</option>
        
                    <option value="CustomerFirstName" id="CustomerFirstName">Tên khách hàng</option>
        
                    <option value="RType" id="RType">Loại phòng</option>
        
                    <option value="Room_id" id="Room_id">Số phòng</option>
                </select>
        
                <input type="submit" value="Tìm kiếm" />
        
            </p>

    }

<div id="gridContent">
    @grid.GetHtml(
    tableStyle: "table table-bordered table-hover",
    footerStyle: "grid-footer",
    fillEmptyRows: true,
    mode: WebGridPagerModes.Numeric,
    alternatingRowStyle: "alternatingRowStyle",
    columns: new[]
    {
            grid.Column("STT",format: item => item.WebGrid.Rows.IndexOf(item) + 1 + Math.Round(Convert.ToDouble(grid.TotalRowCount / grid.PageCount) / grid.RowsPerPage) * grid.RowsPerPage * grid.PageIndex),
            grid.Column("Booking_id", "Mã Booking"),
            grid.Column("CUSTOMER.CustomerLastName", "Họ"),
            grid.Column("CUSTOMER.CustomerFirstName", "Tên"),
            grid.Column("Check_in_date", "Ngày nhận phòng", format:@<text> @item.Check_in_date.ToString("dd/MM/yyyy")</text>),
            grid.Column("Check_out_date", "Ngày trả phòng", format:@<text> @item.Check_out_date.ToString("dd/MM/yyyy")</text>),
            grid.Column("Room_id", "Số phòng"),
            grid.Column("ROOM.ROOMTYPE.RType", "Loại phòng"),
            grid.Column("", format: @<text>


        <form action="/BOOKINGs/Delete/@item.Booking_id" method="POST" class="btn-delete">
            <input type="hidden" name="id" value="@item.Booking_id" />
            @Html.AntiForgeryToken()
            <button type="submit" id="submit" class="btn btn-link btn-delete" onclick="return confirm('Bạn chắc chắn muốn xóa ?');">
                <i class="fas fa-trash-alt text-danger"></i>
            </button>
        </form>
            </text>),
    }

    )
</div>


@section Scripts
{
    <script type="text/javascript">
        var myParam = location.search.split('category=')[1];
        if (myParam) {
            var category = document.getElementById(myParam);
            category.selected = "true";
        }
    </script>
}