Hotel_test1/Controllers/ROOMTYPEsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Hotel_test1.Models;

namespace Hotel_test1.Controllers
{
    public class ROOMTYPEsController : Controller
    {
        private HOTEL3Entities db = new HOTEL3Entities();


        string createId()
        {
            var max = db.ROOMTYPEs.ToList().Select(n => n.RoomType_id).Max();
            int id = int.Parse(max.Substring(2)) + 1;
            string type = String.Concat("0", id.ToString());
            return "RT" + type.Substring(id.ToString().Length - 1);
        }


        // GET: ROOMTYPEs
        public ActionResult Index()
        {
            if (Session["AdminId"] == null || Session["AdminId"].ToString() == "")
            {
                return RedirectToAction("Login", "Admin");
            }

            return View(db.ROOMTYPEs.ToList());
        }

        // GET: ROOMTYPEs/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ROOMTYPE rOOMTYPE = db.ROOMTYPEs.Find(id);
            if (rOOMTYPE == null)
            {
                return HttpNotFound();
            }
            return View(rOOMTYPE);
        }

        // GET: ROOMTYPEs/Create
        public ActionResult Create()
        {
            if (Session["AdminId"] == null || Session["AdminId"].ToString() == "")
            {
                return RedirectToAction("Login", "Admin");
            }
            return View();
        }

        // POST: ROOMTYPEs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(HttpPostedFileBase[] files, [Bind(Include = "RoomType_id,RType,Descriptions,Images,Views,Bed,MaxPerson,Size")] ROOMTYPE rOOMTYPE)
        {
            List<string> listImg = new List<string>();

            if (ModelState.IsValid)
            {

                foreach (HttpPostedFileBase file in files)
                {
                    if (file != null)
                    {
                        string postedFileName = System.IO.Path.GetFileName(file.FileName);
                        var path = System.IO.Path.Combine(Server.MapPath("/images/" + postedFileName));
                        listImg.Add(postedFileName);
                        file.SaveAs(path);
                    }
                }

                rOOMTYPE.RoomType_id = createId();
                rOOMTYPE.Images = string.Join(",", listImg);
                db.ROOMTYPEs.Add(rOOMTYPE);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(rOOMTYPE);
        }

        // GET: ROOMTYPEs/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ROOMTYPE rOOMTYPE = db.ROOMTYPEs.Find(id);
            if (rOOMTYPE == null)
            {
                return HttpNotFound();
            }

            return View(rOOMTYPE);
        }
   

        // POST: ROOMTYPEs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(HttpPostedFileBase[] files, [Bind(Include = "RoomType_id,RType,Descriptions,Images,Views,Bed,MaxPerson,Size")] ROOMTYPE rOOMTYPE)
        {
            List<string> listImg = new List<string>();

           
            if (ModelState.IsValid)
            {
                foreach (HttpPostedFileBase file in files)
                {
                    if (file != null)
                    {
                        string postedFileName = System.IO.Path.GetFileName(file.FileName);
                        var path = System.IO.Path.Combine(Server.MapPath("/images/" + postedFileName));
                        listImg.Add(postedFileName);
                        file.SaveAs(path);
                    }
                }
                //rOOMTYPE.Images = string.Join(",", listImg);

                db.Entry(rOOMTYPE).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(rOOMTYPE);
        }

        // GET: ROOMTYPEs/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ROOMTYPE rOOMTYPE = db.ROOMTYPEs.Find(id);
            if (rOOMTYPE == null)
            {
                return HttpNotFound();
            }
            return View(rOOMTYPE);
        }

        // POST: ROOMTYPEs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            ROOMTYPE rOOMTYPE = db.ROOMTYPEs.Find(id);
            db.ROOMTYPEs.Remove(rOOMTYPE);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Hotel_test1/Views/ROOMTYPEs/Create.cshtml
@model Hotel_test1.Models.ROOMTYPE


@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    ViewBag.Title = "Thêm loại phòng";
}


@using (Html.BeginForm("Create", "ROOMTYPEs", FormMethod.Post, new { enctype =  "multipart/form-data"}))
{
    @Html.AntiForgeryToken()
        
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <!--
        <div class="form-group">
            @Html.LabelFor(model => model.RoomType_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RoomType_id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RoomType_id, "", new { @class = "text-danger" })
            </div>
        </div>
            -->
            
    
        <div class="form-group">
            @Html.LabelFor(model => model.RType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RType, "", new { @class = "text-danger" })
            </div>
        </div>
    
        <div class="form-group">
            @Html.LabelFor(model => model.Descriptions, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descriptions, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descriptions, "", new { @class = "text-danger" })
            </div>
        </div>
    
        <div class="form-group">
            @Html.LabelFor(model => model.Images, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" style="height:30px;" multiple="multiple" name="files" accept="image/*" required />
                    
                <!--
                    @Html.EditorFor(model => model.Images, new { htmlAttributes = new { @class = "form-control" } })
                -->                    
                <!--
                    @Html.ValidationMessageFor(model => model.Images, "", new { @class = "text-danger" })
                -->
            </div>
        </div>
    
        <div class="form-group">
            @Html.LabelFor(model => model.Views, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Views, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Views, "", new { @class = "text-danger" })
            </div>
        </div>
    
        <div class="form-group">
            @Html.LabelFor(model => model.Bed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Bed, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Bed, "", new { @class = "text-danger" })
            </div>
        </div>
    
        <div class="form-group">
            @Html.LabelFor(model => model.MaxPerson, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaxPerson, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaxPerson, "", new { @class = "text-danger" })
            </div>
        </div>
    
        <div class="form-group">
            @Html.LabelFor(model => model.Size, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Size, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Size, "", new { @class = "text-danger" })
            </div>
        </div>
    
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm" class="btn btn-default" />
            </div>
        </div>
    </div>
}
    

Hotel_test1/Views/ROOMTYPEs/Delete.cshtml
@model Hotel_test1.Models.ROOMTYPE

@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>ROOMTYPE</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.RType)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.RType)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Descriptions)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Descriptions)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Images)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Images)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Views)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Views)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Bed)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Bed)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.MaxPerson)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.MaxPerson)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Size)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Size)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

Hotel_test1/Views/ROOMTYPEs/Details.cshtml
@model Hotel_test1.Models.ROOMTYPE

@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    ViewBag.Title = "Thông tin chi tiết";
    string[] listImg = Model.Images.Split(',');
}



<div>
    <h4>Loại phòng <a href="/ROOMTYPEs/Edit/@Model.RoomType_id" class="btn btn-success">Chỉnh sửa</a></h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RType)
        </dt>
    
        <dd>
            @Html.DisplayFor(model => model.RType)
        </dd>
    
        <dt>
            @Html.DisplayNameFor(model => model.Descriptions)
        </dt>
    
        <dd class="detail-description">
            @Html.DisplayFor(model => model.Descriptions)
        </dd>
    
        <dd>
            @Html.DisplayFor(model => model.Size)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Images)
        </dt>

        <dd class="photo">

                @foreach (string img in listImg)
                {
                    <div class="gallery">
                        <a target="_blank" href="~/images/@img">
                            <img src="~/images/@img" alt="@img" width="600" height="400">
                        </a>
                        <!--
                            <div class="desc">Add a description of the image here</div>
                        -->
                    </div>
                }


        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Views)
        </dt>
    
        <dd>
            @Html.DisplayFor(model => model.Views)
        </dd>
    
        <dt>
            @Html.DisplayNameFor(model => model.Bed)
        </dt>
    
        <dd>
            @Html.DisplayFor(model => model.Bed)
        </dd>
    
        <dt>
            @Html.DisplayNameFor(model => model.MaxPerson)
        </dt>
    
        <dd>
            @Html.DisplayFor(model => model.MaxPerson)
        </dd>
    
        <dt>
            @Html.DisplayNameFor(model => model.Size)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Size)
        </dd>

    </dl>
</div>

Hotel_test1/Views/ROOMTYPEs/Edit.cshtml
@model Hotel_test1.Models.ROOMTYPE

@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    ViewBag.Title = "Chỉnh sửa loại phòng";
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script type="text/javascript">
                    $(function ()
                    {
                        var fileupload = $("#files");
                        console.log(fileupload);
                        var image = $("#FileUpload");
                        console.log(image);
                        /*
                        image.click(function ()
                        {
                            fileupload.click();
                        });
                        */
                        fileupload.change(function ()
                        {

                            var list = [];
                            for (let i = 0 ; i < $(this).get(0).files.length; i++) {
                                list.push( $(this).get(0).files[i].name);
                            }

                            console.log(list);

                            //var fileName = $(this).val().split('\\')[$(this).val().split('\\').length - 1];
                            document.getElementById("Images").value = list.join(",");
                            console.log($(this));
                        });
                        console.log("worked");
                    });
    </script>
}



@using (Html.BeginForm("Edit", "ROOMTYPEs", FormMethod.Post, new { id= "edit", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.RoomType_id)

        <div class="form-group">
            @Html.LabelFor(model => model.RType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descriptions, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <textarea form="edit" name="Descriptions">@Model.Descriptions</textarea>
                <!--
                @Html.EditorFor(model => model.Descriptions, new { htmlAttributes = new { @class = "form-control input-description" } })
                    -->
                
                @Html.ValidationMessageFor(model => model.Descriptions, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Images, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Images, new { htmlAttributes = new {@readonly= "readonly", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Images, "", new { @class = "text-danger" })
                <input type="file" style="height:30px;" multiple="multiple" id="files" name="files" accept="image/*" />                
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Views, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Views, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Views, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Bed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Bed, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Bed, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaxPerson, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaxPerson, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaxPerson, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Size, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Size, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Size, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-default" />
            </div>
        </div>
    </div>
}

Hotel_test1/Views/ROOMTYPEs/Index.cshtml
@model IEnumerable<Hotel_test1.Models.ROOMTYPE>

@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    ViewBag.Title = "Danh sách loại phòng";
    var grid = new WebGrid(Model, canPage: true, defaultSort: "RType", rowsPerPage: 5);
}

<div id="gridContent">
    @grid.GetHtml(
    tableStyle: "table table-bordered table-hover",
    footerStyle: "grid-footer",
    fillEmptyRows: true,
    mode: WebGridPagerModes.Numeric,
    alternatingRowStyle: "alternatingRowStyle",
    columns: new[]
    {
            grid.Column("STT",format: item => item.WebGrid.Rows.IndexOf(item) + 1 + Math.Round(Convert.ToDouble(grid.TotalRowCount / grid.PageCount) / grid.RowsPerPage) * grid.RowsPerPage * grid.PageIndex),
            grid.Column("RType", "Loại phòng"),
            grid.Column("Descriptions", "Mô tả", style: "index-description"),
            grid.Column("Views", "View"),
            grid.Column("Bed", "Số giường"),
            grid.Column("MaxPerson", "Số người"),
            grid.Column("Size", "Diện tích"),
            grid.Column("", format: @<text>
                <a href="/ROOMTYPEs/Edit/@item.RoomType_id">
                    <i class='fas fa-edit' title='Edit' id='Edit'></i>
                </a>
                &nbsp;|&nbsp;
                <a href="/ROOMTYPEs/Details/@item.RoomType_id">
                    <i class='fas fa-list-alt' title='Details' id='Details'></i>
                </a>
                &nbsp;|
                <form action="/ROOMTYPEs/Delete/@item.RoomType_id" method="POST" class="btn-delete">
                    <input type="hidden" name="id" value="@item.RoomType_id" />
                    @Html.AntiForgeryToken()
                    <button type="submit" id="submit" class="btn btn-link btn-delete" onclick="return confirm('Bạn chắc chắn muốn xóa ?');">
                        <i class="fas fa-trash-alt text-danger"></i>
                    </button>
                </form>
            </text>),
    }

    )
</div>

<!--
    <table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.RType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descriptions)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Views)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Bed)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MaxPerson)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Size)
        </th>
        <th></th>
    </tr>
    
@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.RType)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descriptions, new { @class = ".index-description" })
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Views)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Bed)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MaxPerson)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Size)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.RoomType_id }) |
            @Html.ActionLink("Details", "Details", new { id=item.RoomType_id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.RoomType_id })
        </td>
    </tr>
}
    
</table>

-->