Hotel_test1/Models/BILL.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_test1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class BILL
    {
        public string Bill_id { get; set; }
        [DisplayName("Tổng tiền")]
        public Nullable<int> Total { get; set; }
        [DisplayName("Mã bill")]
        public string BillPay_id { get; set; }
        [DisplayName("Mã giá phòng")]
        public string Rent_id { get; set; }
        [DisplayName("Mã booking")]
        public string Booking_id { get; set; }

        public virtual BILLPAY BILLPAY { get; set; }
        public virtual BOOKING BOOKING { get; set; }
        public virtual RENT RENT { get; set; }
    }
}

Hotel_test1/Controllers/BILLsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Hotel_test1.Models;

namespace Hotel_test1.Controllers
{
    public class BILLsController : Controller
    {
        private HOTEL3Entities db = new HOTEL3Entities();

        // GET: BILLs
        public ActionResult Index(string searchString, string category)
        {
            if (Session["AdminId"] == null || Session["AdminId"].ToString() == "")
            {
                return RedirectToAction("Login", "Admin");
            }
            var bILLs = db.BILLs.Include(b => b.BILLPAY).Include(b => b.BOOKING).Include(b => b.RENT);


            if (!String.IsNullOrEmpty(searchString))
            {
                if (!String.IsNullOrEmpty(category))
                {
                    ViewBag.category = category;

                    switch (category)
                    {
                        case "Bill_id":
                            bILLs = bILLs.Where(s => s.Bill_id.Contains(searchString));
                            break;
                        case "CustomerLastName":
                            bILLs = bILLs.Where(s => s.BOOKING.CUSTOMER.CustomerLastName.Contains(searchString));
                            break;
                        case "CustomerFirstName":
                            bILLs = bILLs.Where(s => s.BOOKING.CUSTOMER.CustomerFirstName.Contains(searchString));
                            break;
                        case "RType":
                            bILLs = bILLs.Where(s => s.BOOKING.ROOM.ROOMTYPE.RType.Contains(searchString));
                            break;
                    }
                }
            }

            

            return View(bILLs.ToList());
        }



        // GET: BILLs/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BILL bILL = db.BILLs.Find(id);
            if (bILL == null)
            {
                return HttpNotFound();
            }
            return View(bILL);
        }

        // GET: BILLs/Create
        public ActionResult Create()
        {
            ViewBag.BillPay_id = new SelectList(db.BILLPAYs, "BillPay_id", "PayType_id");
            ViewBag.Booking_id = new SelectList(db.BOOKINGs, "Booking_id", "Customer_id");
            ViewBag.Rent_id = new SelectList(db.RENTs, "Rent_id", "RoomType_id");
            return View();
        }

        // POST: BILLs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Bill_id,Total,BillPay_id,Rent_id,Booking_id")] BILL bILL)
        {
            if (ModelState.IsValid)
            {
                db.BILLs.Add(bILL);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.BillPay_id = new SelectList(db.BILLPAYs, "BillPay_id", "PayType_id", bILL.BillPay_id);
            ViewBag.Booking_id = new SelectList(db.BOOKINGs, "Booking_id", "Customer_id", bILL.Booking_id);
            ViewBag.Rent_id = new SelectList(db.RENTs, "Rent_id", "RoomType_id", bILL.Rent_id);
            return View(bILL);
        }

        // GET: BILLs/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BILL bILL = db.BILLs.Find(id);
            if (bILL == null)
            {
                return HttpNotFound();
            }
            ViewBag.BillPay_id = new SelectList(db.BILLPAYs, "BillPay_id", "PayType_id", bILL.BillPay_id);
            ViewBag.Booking_id = new SelectList(db.BOOKINGs, "Booking_id", "Customer_id", bILL.Booking_id);
            ViewBag.Rent_id = new SelectList(db.RENTs, "Rent_id", "RoomType_id", bILL.Rent_id);
            return View(bILL);
        }

        // POST: BILLs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Bill_id,Total,BillPay_id,Rent_id,Booking_id")] BILL bILL)
        {
            if (ModelState.IsValid)
            {
                db.Entry(bILL).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BillPay_id = new SelectList(db.BILLPAYs, "BillPay_id", "PayType_id", bILL.BillPay_id);
            ViewBag.Booking_id = new SelectList(db.BOOKINGs, "Booking_id", "Customer_id", bILL.Booking_id);
            ViewBag.Rent_id = new SelectList(db.RENTs, "Rent_id", "RoomType_id", bILL.Rent_id);
            return View(bILL);
        }

        // GET: BILLs/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BILL bILL = db.BILLs.Find(id);
            if (bILL == null)
            {
                return HttpNotFound();
            }
            return View(bILL);
        }

        // POST: BILLs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            BILL bILL = db.BILLs.Find(id);
            db.BILLs.Remove(bILL);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Hotel_test1/Views/BILLs/Create.cshtml
@model Hotel_test1.Models.BILL

@{
    ViewBag.Title = "Thêm hóa đơn";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>BILL</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Bill_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Bill_id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Bill_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Total, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Total, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Total, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BillPay_id, "BillPay_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BillPay_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BillPay_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rent_id, "Rent_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Rent_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Rent_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Booking_id, "Booking_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Booking_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Booking_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

Hotel_test1/Views/BILLs/Delete.cshtml
@model Hotel_test1.Models.BILL

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BILL</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Total)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BILLPAY.PayType_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BILLPAY.PayType_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BOOKING.Customer_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BOOKING.Customer_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RENT.RoomType_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RENT.RoomType_id)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Hotel_test1/Views/BILLs/Details.cshtml
@model Hotel_test1.Models.BILL

@{
    ViewBag.Title = "Thông tin chi tiết";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <div class="invoice-title">
                <h2>Hóa đơn</h2><br /><h3 class="pull-right">@Html.DisplayFor(model => model.Bill_id)</h3>
            </div>
            <hr>
            <div class="row">
                <div class="col-xs-6">
                    <address>
                        <strong>Hóa đơn tới:</strong><br>
                        @Html.DisplayFor(model => model.BOOKING.CUSTOMER.CustomerLastName) @Html.DisplayFor(model => model.BOOKING.CUSTOMER.CustomerFirstName)<br>
                        @Html.DisplayFor(model => model.BOOKING.CUSTOMER.CustomerTel)<br>
                        @Html.DisplayFor(model => model.BOOKING.CUSTOMER.CustomerEmail)<br>
                    </address>
                </div>

            </div>
            <div class="row">
                <div class="col-xs-6">
                    <address>
                        <strong>Phương thức thanh toán:</strong><br>
                        @Html.DisplayFor(model => model.BILLPAY.PAYTYPE.PType)<br>
                        Thời gian thanh toán: @Html.DisplayFor(model => model.BILLPAY.Date)<br>
                    </address>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><strong>Chi tiết Book:</strong></h3>
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-condensed">
                            <thead>
                                <tr>
                                    <td><strong>Mã book</strong></td>
                                    <td class="text-center"><strong>Số phòng</strong></td>
                                    <td class="text-center"><strong>Loại phòng</strong></td>
                                    <td class="text-center"><strong>Ngày nhận phòng</strong></td>
                                    <td class="text-center"><strong>Ngày trả phòng</strong></td>
                                    <td class="text-right"><strong>Giá 1 đêm</strong></td>
                                </tr>
                            </thead>
                            <tbody>

                                <tr>
                                    <td>@Html.DisplayFor(model => model.Booking_id)</td>
                                    <td class="text-center">@Html.DisplayFor(model => model.BOOKING.Room_id)</td>
                                    <td class="text-center">@Html.DisplayFor(model => model.BOOKING.ROOM.ROOMTYPE.RType)</td>
                                    <td class="text-center">@Html.DisplayFor(model => model.BOOKING.Check_in_date)</td>
                                    <td class="text-center">@Html.DisplayFor(model => model.BOOKING.Check_out_date)</td>
                                    <td class="text-right">@Html.DisplayFor(model => model.RENT.Price)</td>
                                </tr>

                                <tr>
                                    <td class="no-line"></td>
                                    <td class="no-line"></td>
                                    <td class="no-line"></td>
                                    <td class="no-line"></td>
                                    <td class="no-line text-center"><strong>Tổng cộng</strong></td>
                                    <td class="no-line text-right">@Html.DisplayFor(model => model.Total)</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<!--
    
<div>
    <h4>Thông tin chi tiết</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BillPay_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BillPay_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BILLPAY.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BILLPAY.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Booking_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Booking_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BOOKING.CUSTOMER.CustomerLastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BOOKING.CUSTOMER.CustomerLastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BOOKING.CUSTOMER.CustomerFirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BOOKING.CUSTOMER.CustomerFirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BOOKING.Room_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BOOKING.Room_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BOOKING.ROOM.ROOMTYPE.RType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BOOKING.ROOM.ROOMTYPE.RType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RENT.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RENT.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BOOKING.Check_in_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BOOKING.Check_in_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BOOKING.Check_out_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BOOKING.Check_out_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BILLPAY.PAYTYPE.PType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BILLPAY.PAYTYPE.PType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Total)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>


    </dl>
</div>
-->

Hotel_test1/Views/BILLs/Edit.cshtml
@model Hotel_test1.Models.BILL

@{
    ViewBag.Title = "Chỉnh sửa hóa đơn";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>BILL</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Bill_id)

        <div class="form-group">
            @Html.LabelFor(model => model.Total, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Total, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Total, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BillPay_id, "BillPay_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BillPay_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BillPay_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rent_id, "Rent_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Rent_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Rent_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Booking_id, "Booking_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Booking_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Booking_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Hotel_test1/Views/BILLs/Index.cshtml
@model IEnumerable<Hotel_test1.Models.BILL>

@{
    ViewBag.Title = "Danh sách hóa đơn";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    var grid = new WebGrid(Model, canPage: true, defaultSort: "Bill_id", rowsPerPage: 5);
    string category = ViewBag.category;
}


    @using (Html.BeginForm("Index", "BILLs", FormMethod.Get))
    {
    <p>
        

                @Html.TextBox("SearchString")
                <select name="category" id="category">
        
                    <option value="Bill_id" id="Bill_id">Mã bill</option>
        
                    <option value="CustomerLastName" id="CustomerLastName">Họ khách hàng</option>
        
                    <option value="CustomerFirstName" id="CustomerFirstName">Tên khách hàng</option>
        
                    <option value="RType" id="RType">Loại phòng</option>
        
                </select>
        
                <input type="submit" value="Tìm kiếm" />
        
            </p>

    }



<div id="gridContent">
    @grid.GetHtml(
    tableStyle: "table table-bordered table-hover",
    footerStyle: "grid-footer",
    fillEmptyRows: true,
    mode: WebGridPagerModes.Numeric,
    alternatingRowStyle: "alternatingRowStyle",
    columns: new[]
    {
            grid.Column("STT",format: item => item.WebGrid.Rows.IndexOf(item) + 1 + Math.Round(Convert.ToDouble(grid.TotalRowCount / grid.PageCount) / grid.RowsPerPage) * grid.RowsPerPage * grid.PageIndex),
            grid.Column("Bill_id", "Mã bill"),
            grid.Column("BILLPAY.Date", "Ngày thanh toán", format:@<text> @item.BILLPAY.Date.ToString("dd/MM/yyyy")</text>),
            grid.Column("BOOKING.CUSTOMER.CustomerLastName", "Họ"),
            grid.Column("BOOKING.CUSTOMER.CustomerFirstName", "Tên"),
            grid.Column("BOOKING.Room_id", "Số phòng"),
            grid.Column("BOOKING.ROOM.ROOMTYPE.RType", "Loại phòng"),
            grid.Column("Total", "Tổng tiền"),
            grid.Column("", format: @<text>

        <a href="/BILLs/Details/@item.Bill_id">
            <i class='fas fa-list-alt' title='Details' id='Details'></i>
        </a>
        &nbsp;|
        <form action="/BILLs/Delete/@item.Bill_id" method="POST" class="btn-delete">
            <input type="hidden" name="id" value="@item.Bill_id" />
            @Html.AntiForgeryToken()
            <button type="submit" id="submit" class="btn btn-link btn-delete" onclick="return confirm('Bạn chắc chắn muốn xóa ?');">
                <i class="fas fa-trash-alt text-danger"></i>
            </button>
        </form>
            </text>),
    }

    )
</div>

<!--
    

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Total)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BILLPAY.PayType_id)
        </th>
        <td>
            @Html.DisplayNameFor(model => model.BOOKING.CUSTOMER.CustomerFirstName)
        </td>
        <th>
            @Html.DisplayNameFor(model => model.BOOKING.CUSTOMER.CustomerLastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RENT.RoomType_id)
        </th>

    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Total)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BILLPAY.PayType_id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BOOKING.CUSTOMER.CustomerFirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BOOKING.CUSTOMER.CustomerLastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RENT.RoomType_id)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Bill_id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Bill_id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Bill_id })
        </td>
    </tr>
}

</table>

-->

@section Scripts
{
    <script type="text/javascript">
        var myParam = location.search.split('category=')[1];
        if (myParam) {
            var category = document.getElementById(myParam);
            category.selected = "true";
        }
    </script>
}